### PR TITLE
Separate modem reset command from intialization

### PR DESCRIPTION
**Pull request by kscz**
This modification adds in a separate step in modem initialization which
is simply "reset" before sending the init string.

This modification was made to accomodate modems which cannot reset in the
same step as accepting other configuration. This includes the USRobotics
5637 modem - which is generally useful for Linux users where the Conexant
drivers haven't been maintained since kernel version 2.4

### CODE REVIEW

**Comment by kscz** [comment]
Looks like the failure is due to the workflow needing permissions to push to the original repo, not because of code failures

**Comment by hharte** [comment]
@kscz Did you mean to remove the ‘p’ option from optargs?

Otherwise, looks good, thanks!

The workflow failure looks like a bug in my Windows workflow.

**Comment by kscz** [comment]
Ha, no, I did not mean to remove the 'p' option, I just didn't notice I'd deleted it while considering if I should add in a "reset string" option. Fixing it now!

**Comment by kscz** [comment]
Okay - fixed, and I have another PR after this which is basically a "fix a bunch of small type mismatches and other things to make a -Wall -Wextra -Werror pass happy"

**Pull request merged**
